# Generated by Django 6.0.6 on 2026-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadOferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('tipo', models.CharField(choices=[('supermercado', 'Supermercado'), ('banco', 'Banco'), ('otro', 'Otro')], default='supermercado', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
