# Generated by Django 6.0.6 on 2026-06-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tope_reintegro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuotas_disponibles', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('condiciones_legales', models.TextField()),
                ('dias_semana', models.ManyToManyField(related_name='promociones', to='promociones.diasemana')),
                ('entidad_oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='entidades.entidadoferente')),
                ('medios_de_pago', models.ManyToManyField(related_name='promociones', to='promociones.mediodepago')),
                ('supermercados', models.ManyToManyField(related_name='promociones', to='entidades.supermercado')),
            ],
        ),
    ]
